language: rust
rust:
  - stable

# ref. https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry

install:
  - source ~/.cargo/env || true
  - bash ci/install.sh
script:
  - mdbook build
  # - mdbook test
notifications:
  email:
    on_success: never
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: src/doc/book
  on:
    branch: translation
branches:
  only:
    - translation
